# CS224N: PyTorch 入门教程 (2024 春季)

### 作者：Dilara Soylu, Ethan Chi

本 notebook 将对 `PyTorch` 进行基础介绍，并完成一个简单的 NLP 任务。本教程参考了以下资源：
* Matt Lamm 的 ["词窗口分类" 教程 notebook](https://web.stanford.edu/class/archive/cs/cs224n/cs224n.1204/materials/ww_classifier.ipynb)（CS224N 2020 冬季）
* PyTorch 官方文档 [Deep Learning with PyTorch: A 60 Minute Blitz](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html)（Soumith Chintala）
* Sharon Zhou 在 Coursera 上的 PyTorch 教程 [Build Basic Generative Adversarial Networks (GANs)](https://www.coursera.org/learn/build-basic-generative-adversarial-networks-gans)

感谢 Angelica Sun 和 John Hewitt 的反馈。

# 请先复制到您自己的云盘中！

## 简介
[PyTorch](https://pytorch.org/) 是一个深度学习框架，与 [TensorFlow](https://www.tensorflow.org/) 并列为两大主流框架之一。可通过 Pip 或 Conda 安装，详见[此处](https://pytorch.org/)。我们先导入 PyTorch：

In [1]:
import torch
import torch.nn as nn

# 导入 pprint，用于让打印输出更美观
import pprint
pp = pprint.PrettyPrinter()

一切就绪，让我们开始吧！

## 第一部分：张量（Tensors）

**张量**是 PyTorch 中最基础的构建块。每个张量都是一个多维矩阵；例如，一张 256×256 的方形图像可以用 `3x256x256` 的张量表示，其中第一维表示颜色。创建张量的方法如下：


In [3]:
list_of_lists = [
  [1, 2, 3],
  [4, 5, 6],
]
print(list_of_lists)

[[1, 2, 3], [4, 5, 6]]


In [4]:
data = torch.tensor(list_of_lists)
print(data)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# 初始化张量
data = torch.tensor([
                     [0, 1],
                     [2, 3],
                     [4, 5]
                    ])
print(data)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


每个张量都有一个**数据类型**：主要需要关注的是浮点数（`torch.float32`）和整数（`torch.int`）。创建张量时可以显式指定数据类型：

In [ ]:
# 使用显式数据类型初始化张量
# 注意数字后面的点表示它们是浮点数
data = torch.tensor([
                     [0, 1],
                     [2, 3],
                     [4, 5]
                    ], dtype=torch.float32)
print(data)

In [5]:
# 使用显式数据类型初始化张量
# 注意数字后面的点表示它们是浮点数
data = torch.tensor([
                     [0.11111111, 1],
                     [2, 3],
                     [4, 5]
                    ], dtype=torch.float32)
print(data)

tensor([[0.1111, 1.0000],
        [2.0000, 3.0000],
        [4.0000, 5.0000]])


In [6]:
# 使用显式数据类型初始化张量
# 注意数字后面的点表示它们是浮点数
data = torch.tensor([
                     [0.11111111, 1],
                     [2, 3],
                     [4, 5]
                    ])
print(data)

tensor([[0.1111, 1.0000],
        [2.0000, 3.0000],
        [4.0000, 5.0000]])


还有一些工具函数可以创建指定形状和内容的张量：

In [ ]:
zeros = torch.zeros(2, 5)  # 全零张量
print(zeros)

In [ ]:
ones = torch.ones(3, 4)   # 全一张量
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
rr = torch.arange(1, 10) # 范围 [1, 10)
print(rr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
rr + 2

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
rr * 2

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
a = torch.tensor([[1, 2], [2, 3], [4, 5]])      # (3, 2)
b = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])  # (2, 4)

print("A 是", a)
print("B 是", b)
print("乘积为", a.matmul(b)) #(3, 4)
print("另一种乘积写法", a @ b) # +, -, *, @

A is tensor([[1, 2],
        [2, 3],
        [4, 5]])
B is tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
The product is tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])
The other product is tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])


矩阵的**形状**（可通过 `.shape` 访问）即矩阵的维度。以下是一些示例：

In [8]:
matr_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matr_2d.shape)
print(matr_2d)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
matr_3d = torch.tensor([[[1, 2, 3, 4], [-2, 5, 6, 9]], [[5, 6, 7, 2], [8, 9, 10, 4]], [[-3, 2, 2, 1], [4, 6, 5, 9]]])
print(matr_3d)
print(matr_3d.shape)

tensor([[[ 1,  2,  3,  4],
         [-2,  5,  6,  9]],

        [[ 5,  6,  7,  2],
         [ 8,  9, 10,  4]],

        [[-3,  2,  2,  1],
         [ 4,  6,  5,  9]]])
torch.Size([3, 2, 4])


**重塑**张量可以使批量操作更便捷（后面会详细说明），但要注意数据会按你预期的顺序被重塑：

In [9]:
rr = torch.arange(1, 16)
print("当前形状为", rr.shape)
print("当前内容为", rr)
print()
rr = rr.view(5, 3)
print("重塑后形状为", rr.shape)
print("当前内容为", rr)

The shape is currently torch.Size([15])
The contents are currently tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

After reshaping, the shape is currently torch.Size([5, 3])
The contents are currently tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


最后，张量还可以与 **NumPy 数组**相互转换：

In [ ]:
import numpy as np

# numpy.ndarray --> torch.Tensor（NumPy 数组转张量）
arr = np.array([[1, 0, 5]])
data = torch.tensor(arr)
print("这是 torch.tensor", data)

# torch.Tensor --> numpy.ndarray（张量转 NumPy 数组）
new_arr = data.numpy()
print("这是 np.ndarray", new_arr)

This is a torch.tensor tensor([[1, 0, 5]])
This is a np.ndarray [[1 0 5]]


使用**张量**的原因之一是*向量化操作*：可以在张量的某一维度上并行执行的计算。

In [5]:
data = torch.arange(1, 36, dtype=torch.float32).reshape(5, 7)
print("数据为:", data)

# 可以按行进行 *sum* 等操作...
print("按行求和:")
print(data.sum(dim=1)) #(5,)

# 或按列
print("按列求和:")
print(data.sum(dim=0)) #(7,)

# 还有其他操作可用：
print("按行求标准差:")
print(data.std(dim=1))


数据为: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19., 20., 21.],
        [22., 23., 24., 25., 26., 27., 28.],
        [29., 30., 31., 32., 33., 34., 35.]])
按行求和:
tensor([ 28.,  77., 126., 175., 224.])
按列求和:
tensor([ 75.,  80.,  85.,  90.,  95., 100., 105.])
按行求标准差:
tensor([2.1602, 2.1602, 2.1602, 2.1602, 2.1602])


In [6]:
data = torch.arange(1, 7, dtype=torch.float32).reshape(1, 2, 3)
print(data)
print(data.sum(dim=0).sum(dim=0))
print(data.sum(dim=0).sum(dim=0).shape)

tensor([[[1., 2., 3.],
         [4., 5., 6.]]])
tensor([5., 7., 9.])
torch.Size([3])


In [7]:
data.sum()

tensor(21.)

### 小测验

编写代码创建一个包含以下内容的 `torch.tensor`：
$\begin{bmatrix} 1 & 2.2 & 9.6 \\ 4 & -7.2 & 6.3 \end{bmatrix}$

然后计算每行（`.mean()`）和每列的平均值。

结果的形状是什么？



In [9]:
x = torch.tensor([[1,2.2,9.6],[4,-7.2,6.3]])
y = x.mean(dim=0)
print(y)
print(y.shape)
z = x.mean(dim=1)
print(z)
print(z.shape)

tensor([ 2.5000, -2.5000,  7.9500])
torch.Size([3])
tensor([4.2667, 1.0333])
torch.Size([2])


**索引**

可以使用 `[]` 运算符访问张量的任意元素。

In [ ]:
# 初始化示例张量
x = torch.Tensor([
                  [[1, 2], [3, 4]],
                  [[5, 6], [7, 8]],
                  [[9, 10], [11, 12]]
                 ])
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [ ]:
x.shape

torch.Size([3, 2, 2])

In [ ]:
# 访问第 0 个元素，即第一行
x[0] # 等价于 x[0, :]

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
x[:, 0]

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])

也可以使用 `:` 对多个维度进行索引。

In [ ]:
# 获取张量中每个元素的左上角元素
x[:, 0, 0]

tensor([1., 5., 9.])

In [ ]:
x[:, :, :]

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

也可以访问每个维度中的任意元素。

In [ ]:
# 访问第 0 和第 1 个元素，各两次
# 等价于堆叠 x[0], x[0], x[1], x[1]
i = torch.tensor([0, 0, 1, 1])
x[i]

tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]],

        [[5., 6.],
         [7., 8.]]])

In [ ]:
# 访问第 1、2 个元素的第 0 个子元素

i = torch.tensor([1, 2])
j = torch.tensor([0])
x[i, j]

tensor([[ 5.,  6.],
        [ 9., 10.]])

可以使用 `item()` 从张量获取 `Python` 标量值。

In [13]:
x[0, 0, 0]

IndexError: too many indices for tensor of dimension 2

In [12]:
x[0, 0, 0].item()

IndexError: too many indices for tensor of dimension 2

### 练习：

编写代码创建一个包含以下内容的 `torch.tensor`：
$\begin{bmatrix} 1 & 2.2 & 9.6 \\ 4 & -7.2 & 6.3 \end{bmatrix}$

如何获取第一列？第一行？



## 自动求导（Autograd）
PyTorch 以其自动微分功能而闻名。我们可以调用 `backward()` 方法让 PyTorch 计算梯度，梯度会存储在 `grad` 属性中。

In [10]:
# 创建示例张量
# requires_grad 参数告诉 PyTorch 存储梯度
x = torch.tensor([2.], requires_grad=True)

# 打印已计算的梯度
# 当前为 None，因为 x 是标量
pp.pprint(x.grad)

None


In [11]:
# 计算 y 对 x 的梯度
y = x * x * 3 # 3x^2
y.backward()
pp.pprint(x.grad) # d(y)/d(x) = d(3x^2)/d(x) = 6x = 12

tensor([12.])


我们再次从另一个张量运行反向传播，看看会发生什么。

In [12]:
z = x * x * 3 # 3x^2
z.backward()
pp.pprint(x.grad)

tensor([24.])


In [13]:
x.grad = None
z = x * x * 3 # 3x^2
z.backward()
# y = x * x * 3
pp.pprint(x.grad)

tensor([12.])


In [9]:
z = x * x * 3 # 3x^2
z.backward()
# y = x * x * 3
pp.pprint(x.grad)

tensor([24.])


In [14]:
z = x * x * 3 # 3x^2
z.backward()
# y = x * x * 3
pp.pprint(x.grad)

tensor([24.])


可以看到 `x.grad` 被更新为截至目前所计算梯度的累加和。在神经网络中运行反向传播时，我们会在更新参数之前将特定神经元的梯度求和。这里发生的正是这一过程！这也是为什么在每个训练迭代中都需要调用 `zero_grad()` 的原因（稍后详述）。否则梯度会从一个迭代累积到下一个，导致更新出错。

## 自定义反向函数
在某些少见情况下，你可能想设计自己的运算符，或计算 PyTorch 不支持的高阶梯度。此时可以定义自定义的前向和反向计算函数。但请记住，在自定义前向和反向计算之前，务必先检查 PyTorch 是否已有实现（这种可能性很大）。更多内容见 https://pytorch.org/docs/stable/notes/extending.html。

## 神经网络模块

到目前为止我们学习了张量、其属性及基本运算。若从零构建网络层，这些内容会非常有用。我们将在作业 2 中使用它们，但接下来会使用 PyTorch 的 `torch.nn` 模块中的预定义块，并将这些块组合成复杂网络。我们先导入该模块并起别名，这样就不必每次使用时都输入 `torch`。

In [15]:
import torch.nn as nn

### **线性层**
使用 `nn.Linear(H_in, H_out)` 可以创建线性层。输入为 `(N, *, H_in)` 维度的矩阵，输出为 `(N, *, H_out)` 的矩阵。`*` 表示中间可以有任意数量的维度。线性层执行 `Ax+b` 运算，其中 `A` 和 `b` 随机初始化。若不想让线性层学习偏置参数，可用 `bias=False` 初始化。

In [16]:
# 创建输入
input = torch.ones(2,3,4)
# N* H_in -> N*H_out


# 创建线性层，将 N,*,H_in 维输入转换为 N,*,H_out 维输出
linear = nn.Linear(4, 2)
linear_output = linear(input)
linear_output

tensor([[[ 0.0907, -0.0250],
         [ 0.0907, -0.0250],
         [ 0.0907, -0.0250]],

        [[ 0.0907, -0.0250],
         [ 0.0907, -0.0250],
         [ 0.0907, -0.0250]]], grad_fn=<ViewBackward0>)

In [17]:
linear_output.shape

torch.Size([2, 3, 2])

In [18]:
list(linear.parameters()) # Ax + b

[Parameter containing:
 tensor([[ 0.2766,  0.1527,  0.0981, -0.0379],
         [-0.4641,  0.4559,  0.3588, -0.0559]], requires_grad=True),
 Parameter containing:
 tensor([-0.3988, -0.3198], requires_grad=True)]

In [15]:
# Data of shape [batch_size, feature_dim] # 4
# [batch_size, output_dim] # 2

# linear layer of shape (feature_dim, output_dim)

### **其他模块层**
`nn` 模块中还有其他多种预配置层，常用例子包括 `nn.Conv2d`、`nn.ConvTranspose2d`、`nn.BatchNorm1d`、`nn.BatchNorm2d`、`nn.Upsample`、`nn.MaxPool2d` 等。随着课程深入我们会陆续学习。目前只需记住，可将这些层视为即插即用组件：我们提供所需维度，PyTorch 会负责完成搭建。

### **激活函数层**
`nn` 模块也可用于对张量施加激活函数。激活函数为网络引入非线性。例如 `nn.ReLU()`、`nn.Sigmoid()` 和 `nn.LeakyReLU()`。激活函数按元素独立运算，因此输出张量的形状与输入相同。

In [19]:
linear_output

tensor([[[ 0.0907, -0.0250],
         [ 0.0907, -0.0250],
         [ 0.0907, -0.0250]],

        [[ 0.0907, -0.0250],
         [ 0.0907, -0.0250],
         [ 0.0907, -0.0250]]], grad_fn=<ViewBackward0>)

In [17]:
sigmoid = nn.Sigmoid()
output = sigmoid(linear_output)
output

tensor([[[0.5678, 0.2856],
         [0.5678, 0.2856],
         [0.5678, 0.2856]],

        [[0.5678, 0.2856],
         [0.5678, 0.2856],
         [0.5678, 0.2856]]], grad_fn=<SigmoidBackward0>)

### **组合层**
我们已经知道可以创建层并将一层的输出作为下一层的输入。与其创建中间张量并手动传递，不如使用 `nn.Sequential`，它会自动完成这一过程。

In [20]:
block = nn.Sequential(
    nn.Linear(4, 2),
    nn.Sigmoid()
)

input = torch.ones(2,3,4)
output = block(input)
output

tensor([[[0.5707, 0.4570],
         [0.5707, 0.4570],
         [0.5707, 0.4570]],

        [[0.5707, 0.4570],
         [0.5707, 0.4570],
         [0.5707, 0.4570]]], grad_fn=<SigmoidBackward0>)

### 自定义模块

除使用预定义模块外，我们还可以通过继承 `nn.Module` 类来构建自己的模块。例如，可以用前面介绍的张量自行实现 `nn.Linear`（它也继承自 `nn.Module`）！也可以构建更复杂的新模块，如自定义神经网络。你将在后续作业中练习这些内容。

创建自定义模块时，首先需要继承 `nn.Module`。然后在 `__init__` 中初始化参数，并首先调用父类的 `__init__`。所有定义为 `nn` 模块对象的类属性都会被当作可训练参数。张量本身不是参数，但用 `nn.Parameter` 包装后即可成为参数。

继承 `nn.Module` 的类都应实现 `forward(x)` 函数，其中 `x` 为张量。当我们向模块传入参数（如 `model(x)`）时，调用的就是该函数。

In [21]:
class MultilayerPerceptron(nn.Module):

  def __init__(self, input_size, hidden_size):
    # 调用父类的 __init__ 函数
    super(MultilayerPerceptron, self).__init__()

    # 记录：保存初始化参数
    self.input_size = input_size
    self.hidden_size = hidden_size

    # 定义模型
    # `self.model` 的命名无特殊要求，可以是任意名称
    self.model = nn.Sequential(
        nn.Linear(self.input_size, self.hidden_size),
        nn.ReLU(),
        nn.Linear(self.hidden_size, self.input_size),
        nn.Sigmoid()
    )

  def forward(self, x):
    output = self.model(x)
    return output

以下是定义同一类的另一种方式。可以看到，我们可以在 `__init__` 中分别定义各层，并在 `forward` 中串联，从而替代 `nn.Sequential`。

In [22]:
class MultilayerPerceptron(nn.Module):

  def __init__(self, input_size, hidden_size):
    # 调用父类的 __init__ 方法
    super(MultilayerPerceptron, self).__init__()

    # 记录：保存初始化参数
    self.input_size = input_size
    self.hidden_size = hidden_size

    # 定义各层
    self.linear = nn.Linear(self.input_size, self.hidden_size)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(self.hidden_size, self.input_size)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    linear = self.linear(x)
    relu = self.relu(linear)
    linear2 = self.linear2(relu)
    output = self.sigmoid(linear2)
    return output

定义好类后，我们可以实例化它并查看效果。

In [23]:
# 创建示例输入
input = torch.randn(2, 5)

# 创建模型
model = MultilayerPerceptron(5, 3)

# 将输入传入模型
model(input)

tensor([[0.4059, 0.4635, 0.6823, 0.5069, 0.5034],
        [0.5007, 0.4885, 0.6351, 0.4590, 0.4131]], grad_fn=<SigmoidBackward0>)

可以用 `named_parameters()` 和 `parameters()` 方法查看模型的参数。

In [24]:
list(model.named_parameters())

[('linear.weight',
  Parameter containing:
  tensor([[ 0.3256,  0.1448, -0.3273, -0.2210,  0.2575],
          [ 0.2994, -0.2132,  0.3718,  0.3574,  0.3907],
          [ 0.0027, -0.1787, -0.0393,  0.0856, -0.0630]], requires_grad=True)),
 ('linear.bias',
  Parameter containing:
  tensor([ 0.0707, -0.3868, -0.3440], requires_grad=True)),
 ('linear2.weight',
  Parameter containing:
  tensor([[-0.5747,  0.3384,  0.0887],
          [ 0.0275, -0.4304,  0.3969],
          [ 0.3406, -0.2602,  0.0058],
          [ 0.3211, -0.2662, -0.0865],
          [ 0.5313, -0.2762, -0.2345]], requires_grad=True)),
 ('linear2.bias',
  Parameter containing:
  tensor([ 0.0027, -0.0461,  0.5543, -0.1644, -0.3513], requires_grad=True))]

## 优化
我们已介绍了如何用 `backward()` 计算梯度。仅有梯度尚不足以让模型学习，还需要知道如何更新模型参数。优化器（optimizer）就是为此而生。`torch.optim` 模块提供多种优化器，常用的有 `optim.SGD` 和 `optim.Adam`。初始化优化器时，需要传入模型参数（可通过 `model.parameters()` 获取），以指定要优化的变量。优化器还有学习率（`lr`）参数，决定每步更新的幅度。不同优化器还有各自的超参数。

In [25]:
import torch.optim as optim

有了优化函数后，可以定义要优化的 `loss`（损失）。可以自己定义损失，或使用 PyTorch 提供的预定义损失函数，如 `nn.BCELoss()`。下面把所有内容整合起来！先创建一些模拟数据。

In [26]:
# 创建 y 数据
y = torch.ones(10, 5)

# 向目标 y 添加噪声以生成 x
# 我们希望模型能预测原始数据，尽管存在噪声
x = y + torch.randn_like(y)
x

tensor([[ 1.2361,  0.6135,  2.8091,  2.5048,  0.9996],
        [ 0.8226,  0.0663,  0.7898,  2.2792,  0.3939],
        [ 0.2553,  1.1421, -1.8733,  1.7465,  1.4965],
        [ 2.5607, -0.2628,  0.3032,  0.0388,  0.1889],
        [ 1.2151,  2.7813,  0.9759, -0.9392, -0.5199],
        [ 1.4013,  0.5604,  0.7219,  2.7307, -0.2655],
        [ 0.3396,  1.6117,  1.0003,  2.1441,  1.0533],
        [ 0.8394,  0.9642,  1.3297,  0.3939,  3.0385],
        [-0.8600,  0.3208, -0.7346,  1.1757,  0.7299],
        [ 0.4453, -0.9886,  2.0135, -1.6624,  2.9336]])

接下来定义模型、优化器和损失函数。

In [27]:
# 实例化模型
model = MultilayerPerceptron(5, 3)

# 定义优化器
adam = optim.Adam(model.parameters(), lr=1e-1)

# 使用预定义损失函数定义损失
loss_function = nn.MSELoss()

# 计算模型当前表现
y_pred = model(x)
loss_function(y_pred, y).item()

0.2636961042881012

看看能否让模型得到更小的损失。所需内容已齐备，可以设置训练循环了。

In [28]:
# 设置 epoch 数量，决定训练迭代次数
n_epoch = 10

for epoch in range(n_epoch):
  # 将梯度清零
  adam.zero_grad()

  # 获取模型预测
  y_pred = model(x)

  # 计算损失
  loss = loss_function(y_pred, y)

  # 打印统计信息
  print(f"Epoch {epoch}: 训练损失: {loss}")

  # 计算梯度
  loss.backward()

  # 执行一步优化更新权重
  adam.step()


Epoch 0: 训练损失: 0.2636961042881012
Epoch 1: 训练损失: 0.2204447239637375
Epoch 2: 训练损失: 0.17302744090557098
Epoch 3: 训练损失: 0.12500470876693726
Epoch 4: 训练损失: 0.08140837401151657
Epoch 5: 训练损失: 0.04798091948032379
Epoch 6: 训练损失: 0.025396237149834633
Epoch 7: 训练损失: 0.012278459966182709
Epoch 8: 训练损失: 0.0057216607965528965
Epoch 9: 训练损失: 0.002705689985305071


In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3774, -0.2663, -0.2254, -0.3110, -0.0272],
         [ 1.1547,  0.4672,  0.5807,  0.3853,  0.7197],
         [ 0.5740,  1.1962,  0.7437,  0.9969,  1.0613]], requires_grad=True),
 Parameter containing:
 tensor([0.0332, 0.8876, 0.4750], requires_grad=True),
 Parameter containing:
 tensor([[ 0.3789,  0.8695,  0.9322],
         [-0.0926,  0.9584,  0.9451],
         [ 0.1741,  0.5681,  0.5995],
         [-0.5748,  1.1098,  0.6488],
         [-0.0048,  1.2007,  1.2029]], requires_grad=True),
 Parameter containing:
 tensor([0.8713, 1.1602, 0.9818, 0.8432, 0.4917], requires_grad=True)]

可以看到损失在下降。检查模型的预测，看是否接近原始 `y`（全为 `1`）。

In [29]:
# 查看模型在训练数据上的表现
y_pred = model(x)
y_pred

tensor([[0.9999, 0.9998, 0.9999, 0.9998, 0.9887],
        [0.9963, 0.9954, 0.9953, 0.9961, 0.9543],
        [0.9868, 0.9856, 0.9830, 0.9881, 0.9260],
        [0.9821, 0.9791, 0.9791, 0.9901, 0.9295],
        [0.9912, 0.9844, 0.9922, 0.9986, 0.9675],
        [0.9972, 0.9963, 0.9963, 0.9968, 0.9584],
        [0.9993, 0.9989, 0.9991, 0.9990, 0.9753],
        [0.9998, 0.9996, 0.9997, 0.9996, 0.9843],
        [0.9202, 0.9289, 0.9000, 0.9430, 0.8569],
        [0.9949, 0.9938, 0.9935, 0.9948, 0.9484]], grad_fn=<SigmoidBackward0>)

In [ ]:
# 创建测试数据并检查模型表现
x2 = y + torch.randn_like(y)
y_pred = model(x2)
y_pred

tensor([[1.0000, 1.0000, 0.9999, 1.0000, 1.0000],
        [0.9973, 0.9985, 0.9859, 0.9976, 0.9993],
        [1.0000, 1.0000, 0.9997, 1.0000, 1.0000],
        [0.9997, 0.9998, 0.9966, 0.9991, 1.0000],
        [1.0000, 1.0000, 0.9999, 1.0000, 1.0000],
        [0.9983, 0.9990, 0.9893, 0.9971, 0.9996],
        [1.0000, 1.0000, 0.9993, 1.0000, 1.0000],
        [1.0000, 1.0000, 0.9994, 1.0000, 1.0000],
        [0.9999, 1.0000, 0.9988, 0.9999, 1.0000],
        [0.9999, 0.9999, 0.9979, 0.9998, 1.0000]], grad_fn=<SigmoidBackward0>)

很好！模型几乎完美地学会了从输入的 `x` 中过滤掉噪声！

## 演示：词窗口分类（Word Window Classification）

到这部分为止，我们学习了 PyTorch 基础知识并构建了解决简单任务的网络。接下来将尝试完成一个 NLP 示例任务。我们将学习：

1. 数据：创建批量张量数据集
2. 建模
3. 训练
4. 预测

本节目标是训练一个模型，在句子中找到对应 `LOCATION`（地点）的词，且 span 恒为 `1`（即 `San Francisco` 不会被识别为单个 `LOCATION`）。任务之所以叫「词窗口分类」，是因为我们希望模型不仅看单个词，还能考虑上下文。也就是说，对每个词，我们希望模型感知其周围词。开始吧！

### 数据

任何机器学习项目的第一步都是准备训练集。通常会有要使用的训练语料。在 NLP 任务中，语料一般是 `.txt` 或 `.csv` 文件，每行对应一个句子或一条表格数据。在本示例中，我们假设已把数据和对应标签读入 `Python` 列表。

In [30]:
# 原始数据，由句子组成
corpus = [
          "We always come to Paris",
          "The professor is from Australia",
          "I live in Stanford",
          "He comes from Taiwan",
          "The capital of Turkey is Ankara"
         ]

#### 预处理

为便于模型学习，通常会对数据做若干预处理。对文本数据尤其重要。文本预处理示例包括：
* **分词（Tokenization）**：将句子切分为词。
* **小写化（Lowercasing）**：将所有字母转为小写。
* **去噪（Noise removal）**：去除特殊字符（如标点）。
* **停用词去除（Stop words removal）**：去除常用词。

需要哪些预处理步骤取决于具体任务。例如，有些任务适合去除特殊字符，另一些任务（如多语言）则可能需保留。本任务中我们将对小写化并分词。


In [31]:
# 用于生成训练样本的预处理函数
# 函数很简单：将字母小写化并分词
def preprocess_sentence(sentence):
  return sentence.lower().split()

# 创建训练集
train_sentences = [preprocess_sentence(sent) for sent in corpus]
train_sentences

[['we', 'always', 'come', 'to', 'paris'],
 ['the', 'professor', 'is', 'from', 'australia'],
 ['i', 'live', 'in', 'stanford'],
 ['he', 'comes', 'from', 'taiwan'],
 ['the', 'capital', 'of', 'turkey', 'is', 'ankara']]

每个训练样本都应有对应标签。回顾一下，模型目标是判断哪些词对应 `LOCATION`（地点）。即：对非地点词输出 `0`，对地点词输出 `1`。

In [32]:
# 语料中出现的地点集合
locations = set(["australia", "ankara", "paris", "stanford", "taiwan", "turkey"])

# 训练标签
train_labels = [[1 if word in locations else 0 for word in sent] for sent in train_sentences]
train_labels

[[0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 1],
 [0, 0, 0, 1],
 [0, 0, 0, 1, 0, 1]]

#### 将词转换为嵌入（Converting Words to Embeddings）

我们进一步看一下训练数据。每个数据点都是一系列词。另一方面，我们知道机器学习模型处理的是向量形式的数字。如何把词转换成数字？你可能会想到词嵌入（embeddings），没错！

假设我们有一个嵌入查找表 `E`，其中每一行对应一个嵌入向量。也就是说，词汇表中的每个词都对应表中的一行 `i`。每当要查找某个词的嵌入时，可按以下步骤操作：
1. 在嵌入表中找到该词对应的索引 `i`：`word->index`。
2. 用索引查表并获取嵌入：`index->embedding`。

先看第一步。我们需要为词汇表中的每个词分配一个索引。可以这样做：
1. 找出语料中所有不重复的词。
2. 为每个词分配一个索引。

In [34]:
# 查找语料中所有不重复的词
vocabulary = set(w for s in train_sentences for w in s)
vocabulary

{'always',
 'ankara',
 'australia',
 'capital',
 'come',
 'comes',
 'from',
 'he',
 'i',
 'in',
 'is',
 'live',
 'of',
 'paris',
 'professor',
 'stanford',
 'taiwan',
 'the',
 'to',
 'turkey',
 'we'}

`vocabulary` 现已包含语料中所有词。但测试时可能遇到不在词汇表中的词。若能表示这些未知词，模型仍可根据相邻词推断它们是否为 `LOCATION`。

为此我们引入特殊标记 `<unk>` 表示词汇表外的词。也可以用其他字符串，只要该标记唯一且仅用于未知词即可。我们将把该特殊标记加入词汇表。

In [33]:
# 将未知词标记加入词汇表
vocabulary.add("<unk>")

NameError: name 'vocabulary' is not defined

之前提到，任务叫「词窗口分类」是因为模型在做预测时会同时查看目标词及其周围词。

例如句子 "We always come to Paris"，对应标签为 `0, 0, 0, 0, 1`（只有最后一个词 Paris 是 `LOCATION`）。在一次前向传播（即调用 `forward()`）中，模型会尝试为一个词生成正确标签。假设模型要为 `Paris` 生成标签 `1`。若只让模型看到 `Paris`，就无法利用「`to` 常出现在地点词前」这一重要信息。

词窗口让模型在预测时考虑目标词前后各 `+N` 或 `-N` 个词。对 `Paris`，若窗口大小为 1，则查看其前后各一个词，即 `to`，以及…句末之后没有词。这就带来一个问题：`Paris` 在句末，后面没有词。而 PyTorch 模型在初始化时已固定输入维度。若窗口大小为 `1`，模型每次会接收 `3` 个词，不能有时接收 `2` 个。

解决方法是引入特殊填充标记，如 `<pad>`，在句子两端填充，使每个词都有完整的窗口。与 `<unk>` 类似，也可用其他字符串作填充标记，只要用途唯一即可。

In [ ]:
# 将 <pad> 填充标记加入词汇表
vocabulary.add("<pad>")

# 对给定句子进行填充的函数
# 这里先介绍该函数，后续教程会用到
def pad_window(sentence, window_size, pad_token="<pad>"):
  window = [pad_token] * window_size
  return window + sentence + window

# 展示填充示例
window_size = 2
pad_window(train_sentences[0], window_size=window_size)

词汇表已准备好，接下来为每个词分配索引。

In [ ]:
# 将词汇表转为列表以便索引
# 排序非必需，这里排序是为了显示有序的 word_to_ind 字典
# 另外，将填充标记的索引设为 0 比较方便，因为部分 PyTorch 函数（如 nn.utils.rnn.pad_sequence）会将其作为默认值，稍后会介绍
ix_to_word = sorted(list(vocabulary))

# 创建字典以根据词查找索引
word_to_ix = {word: ind for ind, word in enumerate(ix_to_word)}
word_to_ix

In [ ]:
ix_to_word[1]

很好！接下来将训练句子转换为每个 token 对应的索引序列。

In [ ]:
# 给定 token 组成的句子，返回对应索引序列
def convert_token_to_indices(sentence, word_to_ix):
  indices = []
  for token in sentence:
    # 检查 token 是否在词汇表中，在则取其索引
    # 否则取未知词标记的索引
    if token in word_to_ix:
      index = word_to_ix[token]
    else:
      index = word_to_ix["<unk>"]
    indices.append(index)
  return indices

# 更紧凑的相同功能实现
def _convert_token_to_indices(sentence, word_to_ix):
  return [word_to_ind.get(token, word_to_ix["<unk>"]) for token in sentence]

# 示例
example_sentence = ["we", "always", "come", "to", "kuwait"]
example_indices = convert_token_to_indices(example_sentence, word_to_ix)
restored_example = [ix_to_word[ind] for ind in example_indices]

print(f"原句: {example_sentence}")
print(f"词到索引: {example_indices}")
print(f"索引到词: {restored_example}")

上例中 `kuwait` 被表示为 `<unk>`，因为它不在词汇表中。接下来将 `train_sentences` 转换为 `example_padded_indices`。

In [ ]:
# 将句子转换为索引
example_padded_indices = [convert_token_to_indices(s, word_to_ix) for s in train_sentences]
example_padded_indices

词汇表中每个词都有了索引后，可用 PyTorch 的 `nn.Embedding` 类创建嵌入表。调用方式为 `nn.Embedding(num_words, embedding_dimension)`，其中 `num_words` 是词汇量，`embedding_dimension` 是嵌入维度。`nn.Embedding` 本质上是对可训练的 `NxE` 维张量的封装，`N` 为词汇量，`E` 为嵌入维度。该表初始为随机值，训练过程中会更新。随着网络训练，梯度会反向传播到嵌入层，从而更新词嵌入。我们会在模型中初始化嵌入层，这里先展示示例。

In [ ]:
# 创建词嵌入表
embedding_dim = 5
embeds = nn.Embedding(len(vocabulary), embedding_dim)

# 打印嵌入表参数
list(embeds.parameters())

要获取词汇表中某词的嵌入，只需创建查找张量。查找张量就是包含要查找索引的张量。`nn.Embedding` 需要 Long 类型的索引张量，因此创建时要指定 `dtype=torch.long`。

In [ ]:
# 获取 paris 的嵌入
index = word_to_ix["paris"]
index_tensor = torch.tensor(index, dtype=torch.long)
paris_embed = embeds(index_tensor)
paris_embed

In [ ]:
# 也可一次获取多个词的嵌入
index_paris = word_to_ix["paris"]
index_ankara = word_to_ix["ankara"]
indices = [index_paris, index_ankara]
indices_tensor = torch.tensor(indices, dtype=torch.long)
embeddings = embeds(indices_tensor)
embeddings

通常我们会把嵌入层作为模型的一部分定义，在后续章节会看到。

#### 批量处理句子（Batching）

课上已学过批次（batch）。等整个训练语料处理完再更新参数成本很高；而每个样本都更新则会使损失在更新间波动较大。因此我们改为在一个小批次的数据上训练后再更新，从而得到更稳定的梯度估计。本节学习如何用 `torch.utils.data.DataLoader` 将数据组织成批次。

调用方式为：`DataLoader(data, batch_size=batch_size, shuffle=True, collate_fn=collate_fn)`。`batch_size` 决定每批样本数。每个 epoch 会遍历 DataLoader 产生的所有批次。默认批次顺序固定，可将 `shuffle` 设为 `True` 打乱顺序，避免重复遇到同一不利批次。

若提供 `collate_fn`，DataLoader 会把准备好的批次传给该函数。可以自定义该函数以打印统计信息或做额外处理。本例中用 `collate_fn` 完成：
1. 对训练句子进行窗口填充。
2. 将训练样本中的词转换为索引。
3. 填充训练样本使所有句子和标签等长。标签也需填充。但计算损失时要知道每个样本的真实词数，因此在该函数中还需记录这一数量。

由于我们的 `collate_fn` 需要访问 `word_to_ix` 字典（以将词转为索引），会使用 Python 的 `partial` 函数把参数预绑定进去。

In [ ]:
from torch.utils.data import DataLoader
from functools import partial

def custom_collate_fn(batch, window_size, word_to_ix):
  # 将批次拆分为训练样本 (x) 和标签 (y)
  # 将 x 和 y 转为张量，因为 nn.utils.rnn.pad_sequence 需要张量输入
  # 模型也期望张量输入
  x, y = zip(*batch)

  # 对训练样本进行窗口填充，此处再次定义 pad_window 以保持代码完整
  def pad_window(sentence, window_size, pad_token="<pad>"):
    window = [pad_token] * window_size
    return window + sentence + window

  # 填充训练样本
  x = [pad_window(s, window_size=window_size) for s in x]

  # 将训练样本中的词转换为索引
  def convert_tokens_to_indices(sentence, word_to_ix):
    return [word_to_ix.get(token, word_to_ix["<unk>"]) for token in sentence]

  # 转换训练样本为索引
  x = [convert_tokens_to_indices(s, word_to_ix) for s in x]

  # 填充样本使同一批次中所有样本等长，以便矩阵运算
  # batch_first=True 使返回矩阵的首维为批次
  pad_token_ix = word_to_ix["<pad>"]

  # pad_sequence 需要张量输入，将 x 转为张量
  x = [torch.LongTensor(x_i) for x_i in x]
  x_padded = nn.utils.rnn.pad_sequence(x, batch_first=True, padding_value=pad_token_ix)

  # 同时填充标签，并记录每个样本的词数
  lengths = [len(label) for label in y]
  lenghts = torch.LongTensor(lengths)

  y = [torch.LongTensor(y_i) for y_i in y]
  y_padded = nn.utils.rnn.pad_sequence(y, batch_first=True, padding_value=0)

  # 返回变量，顺序与训练循环中读取顺序一致
  return x_padded, y_padded, lenghts

该函数看起来较长，其实可以更简洁。下面是与移除冗余函数定义和注释后的替代版本。

In [ ]:
def _custom_collate_fn(batch, window_size, word_to_ix):
  # 准备数据点
  x, y = zip(*batch)
  x = [pad_window(s, window_size=window_size) for s in x]
  x = [convert_tokens_to_indices(s, word_to_ix) for s in x]

  # 填充 x 使批次中所有样本尺寸相同
  pad_token_ix = word_to_ix["<pad>"]
  x = [torch.LongTensor(x_i) for x_i in x]
  x_padded = nn.utils.rnn.pad_sequence(x, batch_first=True, padding_value=pad_token_ix)

  # 填充 y 并记录每个样本的长度
  lengths = [len(label) for label in y]
  lenghts = torch.LongTensor(lengths)
  y = [torch.LongTensor(y_i) for y_i in y]
  y_padded = nn.utils.rnn.pad_sequence(y, batch_first=True, padding_value=0)

  return x_padded, y_padded, lenghts

下面来实际运行 `DataLoader`。

In [ ]:
# 传入 DataLoader 的参数
data = list(zip(train_sentences, train_labels))
batch_size = 2
shuffle = True
window_size = 2
collate_fn = partial(custom_collate_fn, window_size=window_size, word_to_ix=word_to_ix)

# 实例化 DataLoader
loader = DataLoader(data, batch_size=batch_size, shuffle=shuffle, collate_fn=collate_fn)

# 遍历一次
counter = 0
for batched_x, batched_y, batched_lengths in loader:
  print(f"迭代 {counter}")
  print("批次输入：")
  print(batched_x)
  print("批次标签：")
  print(batched_y)
  print("批次长度：")
  print(batched_lengths)
  print("")
  counter += 1

上面看到的批次输入张量将传入模型。我们说过，模型是一个窗口分类器。当前输入张量的格式是：每个数据点包含句中所有词。将这种输入传给模型时，模型需要为每个词生成窗口，对每个窗口预测中心词是否为 `LOCATION`，再汇总预测并返回。

如果事先把数据切成窗口，可以避免这个问题。本例中我们让模型在内部完成这种格式转换。

设 `window_size` 为 `N`，模型应对每 `2N+1` 个 token 做一次预测。即：若输入有 `9` 个 token，`window_size` 为 `2`，模型应返回 `5` 个预测。这是合理的，因为在两侧各填充 `2` 个 token 之前，句中本来就只有 `5` 个词。

可以用 for 循环创建这些窗口，但 PyTorch 提供了更快的 `unfold(dimension, size, step)` 方法，可以这样创建所需窗口：

In [ ]:
# 打印原始张量
print(f"原始张量：")
print(batched_x)
print("")

# 创建 2*2+1 的窗口块
chunk = batched_x.unfold(1, window_size*2 + 1, 1)
print(f"窗口：")
print(chunk)

### 模型（Model）

数据已准备好，可以开始构建模型。我们已学过如何编写自定义的 `nn.Module` 类，这里将用同样的方式，把目前学到的内容整合在一起。

In [ ]:
class WordWindowClassifier(nn.Module):

  def __init__(self, hyperparameters, vocab_size, pad_ix=0):
    super(WordWindowClassifier, self).__init__()

    """ 实例变量 """
    self.window_size = hyperparameters["window_size"]
    self.embed_dim = hyperparameters["embed_dim"]
    self.hidden_dim = hyperparameters["hidden_dim"]
    self.freeze_embeddings = hyperparameters["freeze_embeddings"]

    """ 嵌入层
    输入包含嵌入索引的张量，返回对应的嵌入向量。输出维度为
    (number_of_indices * embedding_dim)。

    若 freeze_embeddings 为 True，则将嵌入层参数设为不可训练。
    适用于只想更新嵌入层以外参数的情况。

    """
    self.embeds = nn.Embedding(vocab_size, self.embed_dim, padding_idx=pad_ix)
    if self.freeze_embeddings:
      self.embed_layer.weight.requires_grad = False

    """ 隐藏层
    """
    full_window_size = 2 * window_size + 1
    self.hidden_layer = nn.Sequential(
      nn.Linear(full_window_size * self.embed_dim, self.hidden_dim),
      nn.Tanh()
    )

    """ 输出层
    """
    self.output_layer = nn.Linear(self.hidden_dim, 1)

    """ 概率
    """
    self.probabilities = nn.Sigmoid()

  def forward(self, inputs):
    """
    记 B:= batch_size（批次大小）
        L:= window-padded sentence length（填充后句子长度）
        D:= self.embed_dim（嵌入维度）
        S:= self.window_size（窗口大小）
        H:= self.hidden_dim（隐藏层维度）

    inputs: 形状为 (B, L) 的 token 索引张量
    """
    B, L = inputs.size()

    """
    重塑。
    输入 (B, L) LongTensor
    输出 (B, L~, S) LongTensor
    """
    # 首先，为输入中每个词获取其词窗口
    token_windows = inputs.unfold(1, 2 * self.window_size + 1, 1)
    _, adjusted_length, _ = token_windows.size()

    # 建议在内部做张量尺寸一致性检查，至少在注释中说明
    assert token_windows.size() == (B, adjusted_length, 2 * self.window_size + 1)

    """
    嵌入。
    输入形状为 (B, L~, S) 的 torch.LongTensor
    输出 (B, L~, S, D) FloatTensor
    """
    embedded_windows = self.embeds(token_windows)

    """
    重塑。
    输入 (B, L~, S, D) FloatTensor。
    调整为 (B, L~, S*D) FloatTensor。
    -1 表示根据剩余维度自动推断最后一维。
    """
    embedded_windows = embedded_windows.view(B, adjusted_length, -1)

    """
    第 1 层。
    输入 (B, L~, S*D) FloatTensor。
    输出 (B, L~, H) FloatTensor
    """
    layer_1 = self.hidden_layer(embedded_windows)

    """
    第 2 层。
    输入 (B, L~, H) FloatTensor。
    输出 (B, L~, 1) FloatTensor。
    """
    output = self.output_layer(layer_1)

    """
    Sigmoid。
    输入形状为 (B, L~, 1) 的未归一化类别分数 FloatTensor。
    输出形状为 (B, L~, 1) 的归一化类别分数 FloatTensor。
    """
    output = self.probabilities(output)
    output = output.view(B, -1)

    return output

### 训练（Training）

接下来把各部分串起来。先准备数据并初始化模型，然后初始化优化器并定义损失函数。这次我们不再使用内置损失函数，而是自己实现一个。

In [ ]:
# 准备数据
data = list(zip(train_sentences, train_labels))
batch_size = 2
shuffle = True
window_size = 2
collate_fn = partial(custom_collate_fn, window_size=window_size, word_to_ix=word_to_ix)

# 实例化 DataLoader
loader = DataLoader(data, batch_size=batch_size, shuffle=shuffle, collate_fn=collate_fn)

# 初始化模型
# 将模型超参数放在字典中便于管理
model_hyperparameters = {
    "batch_size": 4,
    "window_size": 2,
    "embed_dim": 25,
    "hidden_dim": 25,
    "freeze_embeddings": False,
}

vocab_size = len(word_to_ix)
model = WordWindowClassifier(model_hyperparameters, vocab_size)

# 定义优化器
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# 定义损失函数，计算二值交叉熵损失
def loss_function(batch_outputs, batch_labels, batch_lengths):
    # 计算整个批次的损失
    bceloss = nn.BCELoss()
    loss = bceloss(batch_outputs, batch_labels.float())

    # 对损失进行缩放。lengths 存储了每个训练样本的词数
    loss = loss / batch_lengths.sum().float()

    return loss

与之前的例子不同，这次我们在每个 epoch 中不再一次性传入全部训练数据，而是按批次处理。因此，每个训练 epoch 都会遍历所有批次。

In [ ]:
# 每个 epoch 都会调用的函数
def train_epoch(loss_function, optimizer, model, loader):

  # 记录批次的总损失
  total_loss = 0
  for batch_inputs, batch_labels, batch_lengths in loader:
    # 清空梯度
    optimizer.zero_grad()
    # 执行前向传播
    outputs = model.forward(batch_inputs)
    # 计算批次损失
    loss = loss_function(outputs, batch_labels, batch_lengths)
    # 计算梯度
    loss.backward()
    # 更新参数
    optimizer.step()
    total_loss += loss.item()

  return total_loss


# 包含主训练循环的函数
def train(loss_function, optimizer, model, loader, num_epochs=10000):

  # 遍历每个 epoch 并调用 train_epoch
  for epoch in range(num_epochs):
    epoch_loss = train_epoch(loss_function, optimizer, model, loader)
    if epoch % 100 == 0: print(epoch_loss)

开始训练！

In [ ]:
num_epochs = 1000
train(loss_function, optimizer, model, loader, num_epochs=num_epochs)

### 预测（Prediction）

看看模型在预测上的表现。我们先创建测试数据。

In [ ]:
# 创建测试句子
test_corpus = ["She comes from Paris"]
test_sentences = [s.lower().split() for s in test_corpus]
test_labels = [[0, 0, 0, 1]]

# 创建测试数据加载器
test_data = list(zip(test_sentences, test_labels))
batch_size = 1
shuffle = False
window_size = 2
collate_fn = partial(custom_collate_fn, window_size=2, word_to_ix=word_to_ix)
test_loader = torch.utils.data.DataLoader(test_data,
                                           batch_size=1,
                                           shuffle=False,
                                           collate_fn=collate_fn)

遍历测试样本，看看模型表现如何。

In [ ]:
for test_instance, labels, _ in test_loader:
  outputs = model.forward(test_instance)
  print(labels)
  print(outputs)